linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - gocritic
    - gofmt
    - goimports
    - revive
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - exportloopref
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - unparam
    - misspell
    - nolintlint

run:
  timeout: 3m

issues:
  exclude-rules:
    - text: "exported"
      linters:
        - revive